<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\cabana.glb -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/cabana-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh
      geometry={gltf.nodes.RetopoFlow.geometry}
      material={gltf.materials['Material.024']}
      position={[1.65, 6.79, 1.08]}
      rotation={[0, 0, -0.12]}
    />
    <T.Mesh geometry={gltf.nodes.mesh009.geometry} material={gltf.materials['base_material.013']} />
    <T.Mesh geometry={gltf.nodes.RetopoFlow001.geometry} material={gltf.materials['Material.025']} />
    <T.Mesh
      geometry={gltf.nodes.RetopoFlow002.geometry}
      material={gltf.materials['Material.025']}
      position={[-8.11, 1.43, 7.41]}
      rotation={[0, 0.28, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh100___Square__20_Model.geometry}
      material={gltf.nodes.Mesh100___Square__20_Model.material}
      position={[0, 1.68, 9.49]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh101_Group94_Model.geometry}
      material={gltf.nodes.Mesh101_Group94_Model.material}
      position={[-12.02, 0.47, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model.geometry}
      material={gltf.nodes.Mesh102_Group96_Group95_Model.material}
      position={[-11.8, 0.05, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh106_Group99_Group97_Model.geometry}
      material={gltf.nodes.Mesh106_Group99_Group97_Model.material}
      position={[-10.82, 0.71, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh110___Diamond___Model.geometry}
      material={gltf.nodes.Mesh110___Diamond___Model.material}
      position={[-11.43, 0.26, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh111___Diamond__1_Model.geometry}
      material={gltf.nodes.Mesh111___Diamond__1_Model.material}
      position={[-11.43, 0.55, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh113_Group101_Model.geometry}
      material={gltf.nodes.Mesh113_Group101_Model.material}
      position={[-11.68, 0.39, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh114___Square__25_Group102_Model.geometry}
      material={gltf.nodes.Mesh114___Square__25_Group102_Model.material}
      position={[-11.43, 0.43, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh116___Square__26_Group103_Model.geometry}
      material={gltf.nodes.Mesh116___Square__26_Group103_Model.material}
      position={[-11.18, 0.39, 8.7]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh12_Group19_Model.geometry}
      material={gltf.nodes.Mesh12_Group19_Model.material}
      position={[-1.9, 2.1, -2.49]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh17_Group26_Model.geometry}
      material={gltf.nodes.Mesh17_Group26_Model.material}
      position={[-1.9, 2.1, 3.51]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh120_Model.geometry}
      material={gltf.nodes.Mesh120_Model.material}
      position={[-3.31, 2.02, -1.28]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh19_Group30_Group28_Model.geometry}
      material={gltf.materials['Material.003']}
      position={[1.5, 5.57, 1]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh28_Group39_Group38_Model.geometry}
      material={gltf.materials['Material.004']}
      position={[0.88, 2.89, 1.55]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh39___Square__5_Model.geometry}
      material={gltf.materials['Material.003']}
      position={[-3.14, 2.65, -1.28]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh50___Square__11_Group50_Model.geometry}
      material={gltf.materials['Material.008']}
      position={[-4.18, 6.93, -1.28]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh54_Group52_Model.geometry}
      material={gltf.materials['Material.020']}
      position={[0.35, 1.36, 3.01]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh58_Group56_Model.geometry}
      material={gltf.materials['Material.003']}
      position={[0.83, 3.12, 0.8]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh63_Group59_Model.geometry}
      material={gltf.materials['Material.005']}
      position={[-2.94, 4.67, -0.29]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh75_Group72_Group60_Model.geometry}
      material={gltf.materials['Material.003']}
      position={[-2.72, 0.67, 1.81]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh90_Group85_Group78_Model.geometry}
      material={gltf.materials['Material.003']}
      position={[-5.37, 0.55, -1.12]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh94___Square__19___Archimedes_Spiral__3_Model.geometry}
      material={gltf.materials['Material.001']}
      position={[1.66, 1.6, 1.17]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh99_Group92_Model.geometry}
      material={gltf.materials['Material.009']}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.pared_parte_arriba001.geometry}
      material={gltf.materials['Material.018']}
      position={[0.35, 0.29, 0.21]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh.geometry}
      material={gltf.materials.base_material}
      position={[-10.84, 3.14, -3.15]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={7}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh001.geometry}
      material={gltf.materials.base_material}
      position={[9.11, 3.14, 6.26]}
      rotation={[Math.PI / 2, 0, -1.92]}
      scale={7}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh002.geometry}
      material={gltf.materials['base_material.001']}
      position={[5.61, 0.38, 8.1]}
      rotation={[0, 0.94, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh014.geometry}
      material={gltf.materials['base_material.001']}
      position={[4.74, 0.38, 8.73]}
      rotation={[0, 1.19, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh015.geometry}
      material={gltf.materials['base_material.001']}
      position={[3.99, 0.38, 9.42]}
      rotation={[0, 1.19, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh016.geometry}
      material={gltf.materials['base_material.001']}
      position={[6.65, 0.38, 9.75]}
      rotation={[0, 1.35, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh017.geometry}
      material={gltf.materials['base_material.001']}
      position={[5.86, 0.38, 10.49]}
      rotation={[0, 1.12, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh018.geometry}
      material={gltf.materials['base_material.001']}
      position={[5.1, 0.38, 11.12]}
      rotation={[0, 1.1, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh003.geometry}
      material={gltf.materials['base_material.002']}
      position={[-7.52, 0.42, 9.42]}
      rotation={[Math.PI / 2, 0, 0.72]}
      scale={1.9}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh023.geometry}
      material={gltf.materials['base_material.002']}
      position={[-6.06, 0.42, 7.72]}
      rotation={[Math.PI / 2, 0, 0.72]}
      scale={1.9}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh024.geometry}
      material={gltf.materials['base_material.002']}
      position={[-6.06, 0.42, 7.72]}
      rotation={[Math.PI / 2, 0, 0.72]}
      scale={1.9}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh025.geometry}
      material={gltf.materials['base_material.002']}
      position={[-4.54, 0.42, 8.98]}
      rotation={[Math.PI / 2, 0, 0.72]}
      scale={1.9}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh026.geometry}
      material={gltf.materials['base_material.002']}
      position={[-5.94, 0.42, 10.46]}
      rotation={[Math.PI / 2, 0, 0.45]}
      scale={1.9}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh004.geometry}
      material={gltf.materials['base_material.003']}
      position={[8.47, 2.93, -6.07]}
      rotation={[Math.PI / 2, 0, 0]}
      scale={7}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh005.geometry}
      material={gltf.materials['base_material.004']}
      position={[-12.01, 0.41, -0.02]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh019.geometry}
      material={gltf.materials['base_material.004']}
      position={[7.39, 0.4, 9.41]}
      rotation={[Math.PI / 2, 0, -1.82]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh020.geometry}
      material={gltf.materials['base_material.004']}
      position={[2.87, 0.39, 9.48]}
      rotation={[Math.PI / 2, 0, -1.52]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh022.geometry}
      material={gltf.materials['base_material.004']}
      position={[6.34, 0.4, 7.73]}
      rotation={[Math.PI / 2, 0, -2.49]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh027.geometry}
      material={gltf.materials['base_material.004']}
      position={[-8.41, 0.41, 8.87]}
      rotation={[Math.PI / 2, 0, 1.4]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh028.geometry}
      material={gltf.materials['base_material.004']}
      position={[-6.75, 0.41, 7.06]}
      rotation={[Math.PI / 2, 0, 0.28]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh006.geometry}
      material={gltf.materials['base_material.005']}
      position={[-11.46, 0.41, 2.28]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh021.geometry}
      material={gltf.materials['base_material.005']}
      position={[-2.94, 0.39, 9.78]}
      rotation={[Math.PI / 2, 0, 0.85]}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh007.geometry}
      material={gltf.materials['base_material.006']}
      position={[-8.17, 0.59, 7.38]}
      rotation={[Math.PI / 2, 0, -0.82]}
      scale={2.5}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh008.geometry}
      material={gltf.materials['base_material.007']}
      position={[7.06, 0.4, 8.27]}
      rotation={[Math.PI / 2, 0, 2.55]}
      scale={2}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh010.geometry}
      material={gltf.materials['base_material.009']}
      position={[-1.06, 0.51, 10.11]}
      rotation={[Math.PI / 2, 0, 1.98]}
    />
    <T.Mesh
      geometry={gltf.nodes.pared_parte_arriba003.geometry}
      material={gltf.materials['Material.014']}
      position={[0.69, 4.65, 0.46]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh45___Round__1_Model001.geometry}
      material={gltf.materials['Material.014']}
      position={[-3.31, 6.82, -1.28]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.pared_parte_arriba002.geometry}
      material={gltf.materials['Material.017']}
      position={[0.73, 3.98, 0.32]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh45___Round__1_Model002.geometry}
      material={gltf.materials['Material.018']}
      position={[-3.31, 5.02, -1.28]}
      rotation={[Math.PI / 2, 0, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh75_Group72_Group60_Model001.geometry}
      material={gltf.materials['Material.003']}
      position={[0.38, 0.57, 3.04]}
      rotation={[2.95, 0.08, -2.06]}
      scale={0.93}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh75_Group72_Group60_Model002.geometry}
      material={gltf.materials['Material.003']}
      position={[0.35, 0.99, 3.04]}
      rotation={[2.95, 0.08, -2.06]}
      scale={0.93}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh011.geometry}
      material={gltf.materials['base_material.010']}
      position={[-0.15, 2.78, -8.94]}
      rotation={[Math.PI / 2, 0, 1.16]}
      scale={7}
    />
    <T.Mesh
      geometry={gltf.nodes.mesh012.geometry}
      material={gltf.materials['base_material.011']}
      position={[3.31, 4.53, 2.03]}
      rotation={[Math.PI / 2, 0, Math.PI / 2]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model001.geometry}
      material={gltf.materials['Material.013']}
      position={[-4.78, 0.42, 5.55]}
      rotation={[0, 0.18, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model002.geometry}
      material={gltf.materials['Material.013']}
      position={[5.35, 0.42, 5.27]}
      rotation={[0, -1.34, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model003.geometry}
      material={gltf.materials['Material.013']}
      position={[5, 0.42, -4.83]}
      rotation={[Math.PI, -0.01, Math.PI]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model006.geometry}
      material={gltf.materials['Material.013']}
      position={[-8.22, 0.71, 1.65]}
      rotation={[0, -1.23, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model005.geometry}
      material={gltf.materials['Material.013']}
      position={[-1.27, 0.71, -7.32]}
      rotation={[0, -1.23, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model007.geometry}
      material={gltf.materials['Material.013']}
      position={[8.37, 0.71, 0.9]}
      rotation={[0, -1.39, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model008.geometry}
      material={gltf.materials['Material.013']}
      position={[8.22, 0.71, -0.63]}
      rotation={[0, -1.39, 0]}
    />
    <T.Mesh
      geometry={gltf.nodes.Mesh102_Group96_Group95_Model004.geometry}
      material={gltf.materials['Material.013']}
      position={[-11.21, 0.42, -3.23]}
      rotation={[0, -0.98, 0]}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
