<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\princes1.glb -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/princes1-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature001" rotation={[Math.PI / 2, 0, 0]}>
        <T is={gltf.nodes.mixamorigHips} />
        <T.SkinnedMesh
          name="body002"
          geometry={gltf.nodes.body002.geometry}
          material={gltf.materials['Material.006']}
          skeleton={gltf.nodes.body002.skeleton}
        />
        <T.SkinnedMesh
          name="princess002"
          geometry={gltf.nodes.princess002.geometry}
          material={gltf.nodes.princess002.material}
          skeleton={gltf.nodes.princess002.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
