<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\tumba.glb -T
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf, useGltfAnimations } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/tumba-transformed.glb', { useDraco: true })
  export const { actions, mixer } = useGltfAnimations(gltf, ref)

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group name="Scene">
      <T.Group name="Armature" position={[-0.19, 0.27, 0]} rotation={[0, 0, -Math.PI / 2]}>
        <T is={gltf.nodes.Bone} />
        <T is={gltf.nodes.neutral_bone} />
        <T.SkinnedMesh
          name="mesh001"
          geometry={gltf.nodes.mesh001.geometry}
          material={gltf.materials.base_material}
          skeleton={gltf.nodes.mesh001.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
