<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\farm.glb -T
-->

<script lang="ts">
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf, useGltfAnimations, useProgress } from "@threlte/extras";

  const { active, progress } = useProgress();

  export const ref = new Group();

  const gltf = useGltf("/farm-transformed.glb", { useDraco: true });
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  const component = forwardEventHandlers();
</script>

{#if active}
  <div class="grid place-items-center">
    <p class="text-white">Cargando... {Math.round($progress * 100)}%</p>
  </div>
{/if}

{#if !active}
  <T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
    {#await gltf}
      <slot name="fallback" />
    {:then gltf}
      <T.Group name="Scene">
        <T.Group
          name="Armature001"
          position={[5.33, 0.67, 9.22]}
          rotation={[0, -0.26, 0]}
        >
          <T is={gltf.nodes.Bone} />
          <T.SkinnedMesh
            name="RetopoFlow004"
            geometry={gltf.nodes.RetopoFlow004.geometry}
            material={gltf.materials["base_material.014"]}
            skeleton={gltf.nodes.RetopoFlow004.skeleton}
          />
        </T.Group>
        <T.Group
          name="Armature002"
          position={[5.67, 0.67, 9.59]}
          rotation={[0, -0.26, 0]}
        >
          <T is={gltf.nodes.Bone_1} />
          <T.SkinnedMesh
            name="RetopoFlow005"
            geometry={gltf.nodes.RetopoFlow005.geometry}
            material={gltf.materials["base_material.014"]}
            skeleton={gltf.nodes.RetopoFlow005.skeleton}
          />
        </T.Group>
        <T.Group
          name="Armature003"
          position={[4.69, 0.67, 9.68]}
          rotation={[0, -0.26, 0]}
        >
          <T is={gltf.nodes.Bone_2} />
          <T.SkinnedMesh
            name="RetopoFlow006"
            geometry={gltf.nodes.RetopoFlow006.geometry}
            material={gltf.materials["base_material.014"]}
            skeleton={gltf.nodes.RetopoFlow006.skeleton}
          />
        </T.Group>
        <T.Group
          name="Armature004"
          position={[5.23, 0.67, 9.76]}
          rotation={[0, -0.26, 0]}
        >
          <T is={gltf.nodes.Bone_3} />
          <T.SkinnedMesh
            name="RetopoFlow007"
            geometry={gltf.nodes.RetopoFlow007.geometry}
            material={gltf.materials["base_material.014"]}
            skeleton={gltf.nodes.RetopoFlow007.skeleton}
          />
        </T.Group>
        <T.Group
          name="Armature005"
          position={[5.48, 0.67, 10.21]}
          rotation={[0, -0.26, 0]}
        >
          <T is={gltf.nodes.Bone_4} />
          <T.SkinnedMesh
            name="RetopoFlow008"
            geometry={gltf.nodes.RetopoFlow008.geometry}
            material={gltf.materials["base_material.014"]}
            skeleton={gltf.nodes.RetopoFlow008.skeleton}
          />
        </T.Group>
        <T.Group
          name="Armature006"
          position={[4.67, 0.67, 10.17]}
          rotation={[0, -0.26, 0]}
        >
          <T is={gltf.nodes.Bone_5} />
          <T.SkinnedMesh
            name="RetopoFlow009"
            geometry={gltf.nodes.RetopoFlow009.geometry}
            material={gltf.materials["base_material.014"]}
            skeleton={gltf.nodes.RetopoFlow009.skeleton}
          />
        </T.Group>
        <T.Group name="Armature" position={[3.34, 4.43, 2.03]}>
          <T is={gltf.nodes.Bone_6} />
          <T is={gltf.nodes.Bone003L} />
          <T is={gltf.nodes.Bone003R} />
          <T.SkinnedMesh
            name="mesh012"
            geometry={gltf.nodes.mesh012.geometry}
            material={gltf.materials["base_material.017"]}
            skeleton={gltf.nodes.mesh012.skeleton}
          />
        </T.Group>
        <T.Mesh
          name="RetopoFlow"
          geometry={gltf.nodes.RetopoFlow.geometry}
          material={gltf.materials["Material.024"]}
          position={[1.73, 6.91, 1.07]}
          rotation={[0, 0, -0.12]}
        />
        <T.Mesh
          name="RetopoFlow002"
          geometry={gltf.nodes.RetopoFlow002.geometry}
          material={gltf.materials["Material.027"]}
          position={[-8.12, 2.04, 7.46]}
          rotation={[0, 0.28, 0]}
        />
        <T.Mesh
          name="RetopoFlow047"
          geometry={gltf.nodes.RetopoFlow047.geometry}
          material={gltf.materials["Material.027"]}
          position={[-2.73, 1.21, 1.83]}
          rotation={[0, -0.57, 0]}
          scale={0.56}
        />
        <T.Mesh
          name="RetopoFlow048"
          geometry={gltf.nodes.RetopoFlow048.geometry}
          material={gltf.materials["Material.027"]}
          position={[-4.11, 6.08, 0.01]}
          rotation={[0, -0.25, 0]}
          scale={0.56}
        />
        <T.Mesh
          name="RetopoFlow049"
          geometry={gltf.nodes.RetopoFlow049.geometry}
          material={gltf.materials["Material.027"]}
          position={[-0.77, 1.21, -3.44]}
          rotation={[Math.PI, -1.01, Math.PI]}
          scale={0.56}
        />
        <T.Mesh
          name="RetopoFlow003"
          geometry={gltf.nodes.RetopoFlow003.geometry}
          material={gltf.materials["Material.031"]}
          position={[-5.25, 0.56, 1.68]}
          rotation={[0, -1.57, 0]}
          scale={1.2}
        />
        <T.Mesh
          name="RetopoFlow017"
          geometry={gltf.nodes.RetopoFlow017.geometry}
          material={gltf.materials["Material.039"]}
          position={[-5.31, 0.61, -1.04]}
          scale={0.37}
        />
        <T.Mesh
          name="RetopoFlow036"
          geometry={gltf.nodes.RetopoFlow036.geometry}
          material={gltf.materials["Material.039"]}
          position={[3.75, 0.61, 2.04]}
          rotation={[0, 1.17, 0]}
          scale={0.37}
        />
        <T.Mesh
          name="RetopoFlow037"
          geometry={gltf.nodes.RetopoFlow037.geometry}
          material={gltf.materials["Material.039"]}
          position={[-6.45, 0.61, 2.77]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
          scale={0.37}
        />
        <T.Mesh
          name="RetopoFlow042"
          geometry={gltf.nodes.RetopoFlow042.geometry}
          material={gltf.materials["Material.039"]}
          position={[4.96, 0.61, -0.97]}
          rotation={[Math.PI, -0.61, Math.PI]}
          scale={0.37}
        />
        <T.Mesh
          name="mesh030"
          geometry={gltf.nodes.mesh030.geometry}
          material={gltf.materials["base_material.019"]}
          position={[-5.44, 0.42, -1.89]}
        />
        <T.Mesh
          name="RetopoFlow025"
          geometry={gltf.nodes.RetopoFlow025.geometry}
          material={gltf.materials["Material.044"]}
          position={[-2.88, 0.53, 0.23]}
        />
        <T.Mesh
          name="RetopoFlow018"
          geometry={gltf.nodes.RetopoFlow018.geometry}
          material={gltf.materials["Material.044"]}
          position={[3.04, 0.53, 2.99]}
          rotation={[0.03, -0.05, -0.2]}
        />
        <T.Mesh
          name="RetopoFlow050"
          geometry={gltf.nodes.RetopoFlow050.geometry}
          material={gltf.materials["Material.044"]}
          position={[2.21, 0.53, -2.71]}
          rotation={[-0.13, -0.32, 0.17]}
        />
        <T.Mesh
          name="RetopoFlow026"
          geometry={gltf.nodes.RetopoFlow026.geometry}
          material={gltf.materials["Material.045"]}
          position={[-3.53, 0.54, 0.53]}
          rotation={[0.24, -0.12, 0.01]}
        />
        <T.Mesh
          name="RetopoFlow027"
          geometry={gltf.nodes.RetopoFlow027.geometry}
          material={gltf.materials["Material.046"]}
          position={[-3.36, 0.56, -0.31]}
          rotation={[-0.1, 0.05, 0.07]}
          scale={1.11}
        />
        <T.Mesh
          name="RetopoFlow010"
          geometry={gltf.nodes.RetopoFlow010.geometry}
          material={gltf.materials["Material.046"]}
          position={[-9.4, 0.56, 7.53]}
          rotation={[-0.1, 0.05, 0.07]}
          scale={1.11}
        />
        <T.Mesh
          name="RetopoFlow029"
          geometry={gltf.nodes.RetopoFlow029.geometry}
          material={gltf.materials["Material.041"]}
          position={[-6.12, 0.59, -1.32]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow038"
          geometry={gltf.nodes.RetopoFlow038.geometry}
          material={gltf.materials["Material.041"]}
          position={[-6.29, 0.59, 3.61]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow043"
          geometry={gltf.nodes.RetopoFlow043.geometry}
          material={gltf.materials["Material.041"]}
          position={[5.79, 0.59, -1.2]}
          rotation={[Math.PI, -0.61, Math.PI]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow031"
          geometry={gltf.nodes.RetopoFlow031.geometry}
          material={gltf.materials["Material.042"]}
          position={[-5.66, 0.59, -1.24]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow028"
          geometry={gltf.nodes.RetopoFlow028.geometry}
          material={gltf.materials["Material.042"]}
          position={[-5.69, 0.51, -0.98]}
          rotation={[-1.58, -0.67, 0.47]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow039"
          geometry={gltf.nodes.RetopoFlow039.geometry}
          material={gltf.materials["Material.042"]}
          position={[-6.45, 0.59, 3.18]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow041"
          geometry={gltf.nodes.RetopoFlow041.geometry}
          material={gltf.materials["Material.042"]}
          position={[-6.21, 0.51, 3.08]}
          rotation={[-0.97, 0.3, 2.47]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow044"
          geometry={gltf.nodes.RetopoFlow044.geometry}
          material={gltf.materials["Material.042"]}
          position={[5.37, 0.59, -1.01]}
          rotation={[Math.PI, -0.61, Math.PI]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow046"
          geometry={gltf.nodes.RetopoFlow046.geometry}
          material={gltf.materials["Material.042"]}
          position={[5.25, 0.51, -1.23]}
          rotation={[-1.99, 0.54, -1.94]}
          scale={0.25}
        />
        <T.Mesh
          name="RetopoFlow032"
          geometry={gltf.nodes.RetopoFlow032.geometry}
          material={gltf.materials["Material.043"]}
          position={[-5.91, 0.65, -1.16]}
          scale={0.4}
        />
        <T.Mesh
          name="RetopoFlow030"
          geometry={gltf.nodes.RetopoFlow030.geometry}
          material={gltf.materials["Material.043"]}
          position={[-1.78, 0.24, 3.26]}
          scale={0.47}
        />
        <T.Mesh
          name="RetopoFlow035"
          geometry={gltf.nodes.RetopoFlow035.geometry}
          material={gltf.materials["Material.043"]}
          position={[-2.02, 0.09, 3.22]}
          rotation={[-0.28, -1.19, -2.13]}
          scale={0.47}
        />
        <T.Mesh
          name="RetopoFlow040"
          geometry={gltf.nodes.RetopoFlow040.geometry}
          material={gltf.materials["Material.043"]}
          position={[-6.25, 0.65, 3.35]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
          scale={0.4}
        />
        <T.Mesh
          name="RetopoFlow045"
          geometry={gltf.nodes.RetopoFlow045.geometry}
          material={gltf.materials["Material.043"]}
          position={[5.53, 0.65, -1.21]}
          rotation={[Math.PI, -0.61, Math.PI]}
          scale={0.4}
        />
        <T.Mesh
          name="mesh031"
          geometry={gltf.nodes.mesh031.geometry}
          material={gltf.materials["base_material.018"]}
          position={[-4.82, 0.62, -1.15]}
          scale={0.63}
        />
        <T.Mesh
          name="mesh035"
          geometry={gltf.nodes.mesh035.geometry}
          material={gltf.materials["base_material.018"]}
          position={[3.84, 0.62, 1.55]}
          rotation={[0, 1.17, 0]}
          scale={0.63}
        />
        <T.Mesh
          name="mesh038"
          geometry={gltf.nodes.mesh038.geometry}
          material={gltf.materials["base_material.018"]}
          position={[-6.79, 0.62, 2.4]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
          scale={0.63}
        />
        <T.Mesh
          name="mesh033"
          geometry={gltf.nodes.mesh033.geometry}
          material={gltf.materials["base_material.019"]}
          position={[4.77, 0.42, -0.49]}
        />
        <T.Mesh
          name="mesh037"
          geometry={gltf.nodes.mesh037.geometry}
          material={gltf.materials["base_material.019"]}
          position={[-7.12, 0.41, 3.31]}
          rotation={[-Math.PI, 1.05, -Math.PI]}
        />
        <T.Mesh
          name="mesh041"
          geometry={gltf.nodes.mesh041.geometry}
          material={gltf.materials["base_material.021"]}
          position={[5.79, 0.23, 0.8]}
          scale={1.45}
        />
        <T.Mesh
          name="Cube"
          geometry={gltf.nodes.Cube.geometry}
          material={gltf.materials["Material.048"]}
          position={[2.7, 0.32, 3.45]}
          rotation={[-0.52, 0.62, 0.67]}
          scale={0.17}
        />
        <T.Mesh
          name="Cube001"
          geometry={gltf.nodes.Cube001.geometry}
          material={gltf.materials["Material.048"]}
          position={[5.3, -0.83, 9.7]}
          rotation={[-2.37, -0.3, -2.63]}
          scale={0.82}
        />
        <T.Mesh
          name="Cube002"
          geometry={gltf.nodes.Cube002.geometry}
          material={gltf.materials["Material.048"]}
          position={[-2.64, 0.43, 3.23]}
          scale={0.17}
        />
        <T.Mesh
          name="Cube003"
          geometry={gltf.nodes.Cube003.geometry}
          material={gltf.materials["Material.048"]}
          position={[0.8, 0.32, -2.82]}
          rotation={[-0.52, 0.62, 0.67]}
          scale={0.17}
        />
        <T.Mesh
          name="Cube004"
          geometry={gltf.nodes.Cube004.geometry}
          material={gltf.materials["Material.048"]}
          position={[0.41, 0.33, -2.97]}
          rotation={[-1.43, -1.31, -2.4]}
          scale={0.17}
        />
        <T.Mesh
          name="Cube005"
          geometry={gltf.nodes.Cube005.geometry}
          material={gltf.materials["Material.048"]}
          position={[-6.02, -0.83, 9.06]}
          rotation={[-1.03, -0.67, -0.57]}
          scale={0.82}
        />
        <T.Mesh
          name="Cube006"
          geometry={gltf.nodes.Cube006.geometry}
          material={gltf.materials["Material.048"]}
          position={[-4.5, -0.85, 4.62]}
          rotation={[-0.84, -0.46, -0.24]}
          scale={0.82}
        />
        <T.Mesh
          name="Cube007"
          geometry={gltf.nodes.Cube007.geometry}
          material={gltf.materials["Material.048"]}
          position={[4.27, -0.85, 4.75]}
          rotation={[-0.88, 0.52, 0.77]}
          scale={0.82}
        />
        <T.Mesh
          name="Cube008"
          geometry={gltf.nodes.Cube008.geometry}
          material={gltf.materials["Material.048"]}
          position={[4.27, -0.79, -4.82]}
          rotation={[-1.76, 0.82, 2.05]}
          scale={0.82}
        />
        <T.Mesh
          name="Cube009"
          geometry={gltf.nodes.Cube009.geometry}
          material={gltf.materials["Material.048"]}
          position={[-4.47, -0.84, -4.83]}
          rotation={[-1.16, 0.63, 1.71]}
          scale={0.82}
        />
        <T.Mesh
          name="Mesh100___Square__20_Model"
          geometry={gltf.nodes.Mesh100___Square__20_Model.geometry}
          material={gltf.materials["Material.049"]}
          position={[0, 1.68, 9.49]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh12_Group19_Model"
          geometry={gltf.nodes.Mesh12_Group19_Model.geometry}
          material={gltf.nodes.Mesh12_Group19_Model.material}
          position={[-1.9, 2.1, -2.49]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh17_Group26_Model"
          geometry={gltf.nodes.Mesh17_Group26_Model.geometry}
          material={gltf.nodes.Mesh17_Group26_Model.material}
          position={[-1.9, 2.1, 3.51]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh120_Model"
          geometry={gltf.nodes.Mesh120_Model.geometry}
          material={gltf.nodes.Mesh120_Model.material}
          position={[-3.31, 2.02, -1.28]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh19_Group30_Group28_Model"
          geometry={gltf.nodes.Mesh19_Group30_Group28_Model.geometry}
          material={gltf.materials["Material.003"]}
          position={[1.5, 5.57, 1]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh28_Group39_Group38_Model"
          geometry={gltf.nodes.Mesh28_Group39_Group38_Model.geometry}
          material={gltf.materials["Material.004"]}
          position={[0.88, 2.89, 1.55]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh39___Square__5_Model"
          geometry={gltf.nodes.Mesh39___Square__5_Model.geometry}
          material={gltf.materials["Material.003"]}
          position={[-3.14, 2.65, -1.28]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh50___Square__11_Group50_Model"
          geometry={gltf.nodes.Mesh50___Square__11_Group50_Model.geometry}
          material={gltf.materials["Material.008"]}
          position={[-4.18, 6.93, -1.28]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh54_Group52_Model"
          geometry={gltf.nodes.Mesh54_Group52_Model.geometry}
          material={gltf.materials["Material.020"]}
          position={[0.35, 1.36, 3.01]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh58_Group56_Model"
          geometry={gltf.nodes.Mesh58_Group56_Model.geometry}
          material={gltf.materials["Material.003"]}
          position={[0.83, 3.12, 0.8]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh63_Group59_Model"
          geometry={gltf.nodes.Mesh63_Group59_Model.geometry}
          material={gltf.materials["Material.005"]}
          position={[-2.94, 4.67, -0.29]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh75_Group72_Group60_Model"
          geometry={gltf.nodes.Mesh75_Group72_Group60_Model.geometry}
          material={gltf.materials["Material.003"]}
          position={[-2.72, 0.67, 1.81]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh75_Group72_Group60_Model003"
          geometry={gltf.nodes.Mesh75_Group72_Group60_Model003.geometry}
          material={gltf.materials["Material.003"]}
          position={[-0.76, 0.67, -3.43]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <T.Mesh
          name="Mesh90_Group85_Group78_Model"
          geometry={gltf.nodes.Mesh90_Group85_Group78_Model.geometry}
          material={gltf.materials["Material.003"]}
          position={[-5.37, 0.25, -1.12]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh90_Group85_Group78_Model001"
          geometry={gltf.nodes.Mesh90_Group85_Group78_Model001.geometry}
          material={gltf.materials["Material.003"]}
          position={[5.57, 0.26, -1.12]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh90_Group85_Group78_Model002"
          geometry={gltf.nodes.Mesh90_Group85_Group78_Model002.geometry}
          material={gltf.materials["Material.003"]}
          position={[3.82, 0.26, 1.74]}
          rotation={[Math.PI / 2, 0, 1.2]}
        />
        <T.Mesh
          name="Mesh90_Group85_Group78_Model003"
          geometry={gltf.nodes.Mesh90_Group85_Group78_Model003.geometry}
          material={gltf.materials["Material.003"]}
          position={[-6.49, 0.25, 2.86]}
          rotation={[Math.PI / 2, 0, -2.09]}
        />
        <T.Mesh
          name="Mesh94___Square__19___Archimedes_Spiral__3_Model"
          geometry={gltf.nodes.Mesh94___Square__19___Archimedes_Spiral__3_Model
            .geometry}
          material={gltf.materials["Material.001"]}
          position={[1.72, 1.59, 1.17]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="pared_parte_arriba001"
          geometry={gltf.nodes.pared_parte_arriba001.geometry}
          material={gltf.materials["Material.018"]}
          position={[0.35, 0.29, 0.21]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="mesh"
          geometry={gltf.nodes.mesh.geometry}
          material={gltf.materials.base_material}
          position={[-10.91, 3.09, -3.16]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={7}
        />
        <T.Mesh
          name="mesh001"
          geometry={gltf.nodes.mesh001.geometry}
          material={gltf.materials.base_material}
          position={[9.13, 3.09, 6.32]}
          rotation={[Math.PI / 2, 0, -1.92]}
          scale={7}
        />
        <T.Mesh
          name="mesh002"
          geometry={gltf.nodes.mesh002.geometry}
          material={gltf.materials["base_material.001"]}
          position={[4.79, 0.42, 8.74]}
          rotation={[0, 0.94, 0]}
        />
        <T.Mesh
          name="mesh004"
          geometry={gltf.nodes.mesh004.geometry}
          material={gltf.materials["base_material.003"]}
          position={[8.48, 2.89, -6.09]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={7}
        />
        <T.Group
          name="mesh005"
          position={[-10.74, 0.39, -1.7]}
          rotation={[Math.PI / 2, 0, 1.21]}
        >
          <T.Mesh
            name="mesh005_1"
            geometry={gltf.nodes.mesh005_1.geometry}
            material={gltf.materials["base_material.004"]}
          />
          <T.Mesh
            name="mesh005_2"
            geometry={gltf.nodes.mesh005_2.geometry}
            material={gltf.materials["base_material.005"]}
          />
        </T.Group>
        <T.Mesh
          name="mesh008"
          geometry={gltf.nodes.mesh008.geometry}
          material={gltf.materials["base_material.007"]}
          position={[7.06, 0.4, 8.27]}
          rotation={[Math.PI / 2, 0, 2.55]}
          scale={2}
        />
        <T.Mesh
          name="mesh010"
          geometry={gltf.nodes.mesh010.geometry}
          material={gltf.materials["base_material.009"]}
          position={[-1.06, 0.51, 10.11]}
          rotation={[Math.PI / 2, 0, 1.98]}
        />
        <T.Mesh
          name="pared_parte_arriba003"
          geometry={gltf.nodes.pared_parte_arriba003.geometry}
          material={gltf.materials["Material.014"]}
          position={[0.69, 4.65, 0.46]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh45___Round__1_Model001"
          geometry={gltf.nodes.Mesh45___Round__1_Model001.geometry}
          material={gltf.materials["Material.014"]}
          position={[-3.31, 6.82, -1.28]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="pared_parte_arriba002"
          geometry={gltf.nodes.pared_parte_arriba002.geometry}
          material={gltf.materials["Material.017"]}
          position={[0.73, 3.98, 0.32]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh45___Round__1_Model002"
          geometry={gltf.nodes.Mesh45___Round__1_Model002.geometry}
          material={gltf.materials["Material.018"]}
          position={[-3.31, 5.02, -1.28]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <T.Mesh
          name="Mesh75_Group72_Group60_Model001"
          geometry={gltf.nodes.Mesh75_Group72_Group60_Model001.geometry}
          material={gltf.materials["Material.003"]}
          position={[0.38, 0.57, 3.04]}
          rotation={[2.95, 0.08, -2.06]}
          scale={0.93}
        />
        <T.Mesh
          name="Mesh75_Group72_Group60_Model002"
          geometry={gltf.nodes.Mesh75_Group72_Group60_Model002.geometry}
          material={gltf.materials["Material.003"]}
          position={[0.35, 0.99, 3.04]}
          rotation={[2.95, 0.08, -2.06]}
          scale={0.93}
        />
        <T.Mesh
          name="mesh011"
          geometry={gltf.nodes.mesh011.geometry}
          material={gltf.materials["base_material.010"]}
          position={[-0.15, 2.76, -8.96]}
          rotation={[Math.PI / 2, 0, 1.16]}
          scale={7}
        />
        <T.Mesh
          name="mesh042"
          geometry={gltf.nodes.mesh042.geometry}
          material={gltf.materials["base_material.010"]}
          position={[-9.92, 2.76, 5.54]}
          rotation={[Math.PI / 2, 0, 1.56]}
          scale={7}
        />
        <T.Mesh
          name="mesh013"
          geometry={gltf.nodes.mesh013.geometry}
          material={gltf.materials["base_material.012"]}
          position={[1.67, 6.83, 1.01]}
          rotation={[Math.PI / 2, -0.15, Math.PI / 2]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model001"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model001.geometry}
          material={gltf.materials["Material.013"]}
          position={[-4.78, 0.42, 5.55]}
          rotation={[0, 0.18, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model002"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model002.geometry}
          material={gltf.materials["Material.013"]}
          position={[5.35, 0.42, 5.27]}
          rotation={[0, -1.34, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model003"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model003.geometry}
          material={gltf.materials["Material.013"]}
          position={[5, 0.42, -4.83]}
          rotation={[Math.PI, -0.01, Math.PI]}
        />
        <T.Mesh
          name="mesh016"
          geometry={gltf.nodes.mesh016.geometry}
          material={gltf.materials["base_material.001"]}
          position={[5.88, 0.42, 10.45]}
          rotation={[0, 1.35, 0]}
        />
        <T.Group
          name="mesh021"
          position={[-0.66, 0.37, 9.66]}
          rotation={[Math.PI / 2, 0, 0.85]}
        >
          <T.Mesh
            name="mesh021_1"
            geometry={gltf.nodes.mesh021_1.geometry}
            material={gltf.materials["base_material.005"]}
          />
          <T.Mesh
            name="mesh021_2"
            geometry={gltf.nodes.mesh021_2.geometry}
            material={gltf.materials["base_material.004"]}
          />
        </T.Group>
        <T.Mesh
          name="mesh022"
          geometry={gltf.nodes.mesh022.geometry}
          material={gltf.materials["base_material.004"]}
          position={[6.87, 0.4, 8.58]}
          rotation={[Math.PI / 2, 0, -2.49]}
        />
        <T.Mesh
          name="mesh024"
          geometry={gltf.nodes.mesh024.geometry}
          material={gltf.materials["base_material.002"]}
          position={[-6.05, 0.43, 7.73]}
          rotation={[Math.PI / 2, 0, 0.72]}
          scale={1.9}
        />
        <T.Mesh
          name="mesh025"
          geometry={gltf.nodes.mesh025.geometry}
          material={gltf.materials["base_material.002"]}
          position={[-6, 0.43, 9.15]}
          rotation={[Math.PI / 2, 0, 0.72]}
          scale={1.9}
        />
        <T.Mesh
          name="mesh027"
          geometry={gltf.nodes.mesh027.geometry}
          material={gltf.materials["base_material.004"]}
          position={[-7.58, 0.41, 7.96]}
          rotation={[Math.PI / 2, 0, 1.4]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model009"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model009.geometry}
          material={gltf.materials["Material.013"]}
          position={[-4.78, 0.42, 5.55]}
          rotation={[0, 0.18, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model010"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model010.geometry}
          material={gltf.materials["Material.013"]}
          position={[-4.78, 0.42, 5.55]}
          rotation={[0, 0.18, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model011"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model011.geometry}
          material={gltf.materials["Material.013"]}
          position={[-8.15, 0.71, 1.67]}
          rotation={[0, 0.18, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model006"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model006.geometry}
          material={gltf.materials["Material.013"]}
          position={[8.4, 0.71, 0.93]}
          rotation={[0, 0.18, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model007"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model007.geometry}
          material={gltf.materials["Material.013"]}
          position={[8.2, 0.71, -0.6]}
          rotation={[0, 0.18, 0]}
        />
        <T.Mesh
          name="Mesh102_Group96_Group95_Model004"
          geometry={gltf.nodes.Mesh102_Group96_Group95_Model004.geometry}
          material={gltf.materials["Material.013"]}
          position={[-5.71, 0.42, -5.27]}
        />
        <T.Mesh
          name="mesh032"
          geometry={gltf.nodes.mesh032.geometry}
          material={gltf.materials["base_material.004"]}
          position={[-1.07, 0.24, -6.89]}
          rotation={[Math.PI / 2, 0, 1.21]}
          scale={0.64}
        />
        <T.Mesh
          name="mesh036"
          geometry={gltf.nodes.mesh036.geometry}
          material={gltf.materials["base_material.005"]}
          position={[8.98, 0.39, 5.97]}
          rotation={[Math.PI / 2, 0, 1.63]}
        />
        <T.Mesh
          name="mesh039"
          geometry={gltf.nodes.mesh039.geometry}
          material={gltf.materials["base_material.005"]}
          position={[8.83, 0.21, 1.01]}
          rotation={[Math.PI / 2, 0, -1.7]}
          scale={0.54}
        />
        <T.Mesh
          name="mesh043"
          geometry={gltf.nodes.mesh043.geometry}
          material={gltf.materials["base_material.002"]}
          position={[-10.23, 0.43, -6.85]}
          rotation={[Math.PI / 2, 0, -0.7]}
          scale={1.9}
        />
        <T.Mesh
          name="mesh050"
          geometry={gltf.nodes.mesh050.geometry}
          material={gltf.materials["base_material.002"]}
          position={[6.16, 0.43, -10.32]}
          rotation={[Math.PI / 2, 0, 0.22]}
          scale={1.9}
        />
        <T.Mesh
          name="mesh014"
          geometry={gltf.nodes.mesh014.geometry}
          material={gltf.materials["base_material.006"]}
          position={[-8.26, 0.6, 7.43]}
          rotation={[Math.PI / 2, 0, -0.82]}
          scale={2.5}
        />
        <T.Mesh
          name="mesh015"
          geometry={gltf.nodes.mesh015.geometry}
          material={gltf.materials["base_material.005"]}
          position={[8.33, 0.39, -5.31]}
          rotation={[Math.PI / 2, 0, 1.16]}
        />
        <T.Group
          name="mesh018"
          position={[-10.27, 0.39, 5.53]}
          rotation={[Math.PI / 2, 0, 0.04]}
        >
          <T.Mesh
            name="mesh063"
            geometry={gltf.nodes.mesh063.geometry}
            material={gltf.materials["base_material.004"]}
          />
          <T.Mesh
            name="mesh063_1"
            geometry={gltf.nodes.mesh063_1.geometry}
            material={gltf.materials["base_material.005"]}
          />
        </T.Group>
        <T.Group
          name="mesh026"
          position={[-0.32, 0.37, -8.54]}
          rotation={[Math.PI / 2, 0, 0.7]}
        >
          <T.Mesh
            name="mesh065"
            geometry={gltf.nodes.mesh065.geometry}
            material={gltf.materials["base_material.004"]}
          />
          <T.Mesh
            name="mesh065_1"
            geometry={gltf.nodes.mesh065_1.geometry}
            material={gltf.materials["base_material.005"]}
          />
        </T.Group>
        <T.Mesh
          name="Circle"
          geometry={gltf.nodes.Circle.geometry}
          material={gltf.materials["Material.053"]}
          position={[0, -0.96, 0]}
          scale={14.01}
        />
        <T.Mesh
          name="Circle001"
          geometry={gltf.nodes.Circle001.geometry}
          material={gltf.materials["Material.054"]}
          position={[0, -4.58, 0]}
          scale={14.01}
        />
        <T.Mesh
          name="stand"
          geometry={gltf.nodes.stand.geometry}
          material={gltf.nodes.stand.material}
          position={[-1.19, 1.02, 10.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.6}
        />
        <T.Mesh
          name="stand001"
          geometry={gltf.nodes.stand001.geometry}
          material={gltf.nodes.stand001.material}
          position={[1.21, 1.02, 10.03]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.6}
        />
      </T.Group>
    {:catch error}
      <slot name="error" {error} />
    {/await}

    <slot {ref} />
  </T>
{/if}
