<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\tumba.glb -T
-->

<script lang="ts">
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf, useGltfAnimations, HTML } from "@threlte/extras";
  import { isOpen } from "../../stores/stores";

  export const ref = new Group();

  const gltf = useGltf("/tumba-transformed.glb", { useDraco: true });
  export const { actions, mixer } = useGltfAnimations(gltf, ref);

  const component = forwardEventHandlers();

  // $: {
  //   if ($actions.open) {
  //     // console.log($actions);
  //     $actions.open.repetitions = 1;
  //     $actions.open.time = 5000;
  //     $actions.open.play();
  //   }
  // }

  const open = (e: Event) => {
    e.preventDefault();
    if ($actions.open && $isOpen === false) {
      $actions.open.paused = false;
      $actions.open.play();
      $actions.open.setDuration(2);
      $actions.open.clampWhenFinished = true;
      setTimeout(() => {
        //@ts-ignore
        $actions.open.paused = true;
        $isOpen = true;
      }, 1900);
    }
  };

  const close = (e: Event) => {
    e.preventDefault();
    if ($actions.open && $isOpen === true) {
      $actions.open.fadeOut(2);
      setTimeout(() => {
        $isOpen = false;
        $actions.open?.stop();
      }, 2000);
    }
  };
</script>

<HTML position={[-1.2, 0.5, 0]} rotation={[0, 0, 0]} scale={0.5} transform>
  <button on:click={open}>Open </button>
</HTML>

<HTML position={[1.2, 0.5, 0]} rotation={[0, 0, 0]} scale={0.5} transform >
  <button on:click={close}>Close </button>
</HTML>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0.24, 0]} name="Scene">
      <T.Group
        name="Armature"
        position={[-0.19, 0.27, 0]}
        rotation={[0, 0, -Math.PI / 2]}
      >
        <T is={gltf.nodes.Bone} />
        <T is={gltf.nodes.neutral_bone} />
        <T.SkinnedMesh
          name="mesh001"
          geometry={gltf.nodes.mesh001.geometry}
          material={gltf.materials.base_material}
          skeleton={gltf.nodes.mesh001.skeleton}
        />
      </T.Group>
    </T.Group>
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
